# Generated by Django 3.1 on 2020-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200906_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='descrpition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
