# Generated by Django 3.1 on 2020-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200918_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fligt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descrpition', models.CharField(max_length=182)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
