# Generated by Django 3.1 on 2020-09-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_fligt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fligt',
        ),
    ]
