# Generated by Django 3.1 on 2020-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
