# Generated by Django 3.1 on 2020-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='create',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='value',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
