# Generated by Django 3.1 on 2020-10-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201001_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='value',
        ),
    ]
